name: binder-env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - numpy=1.26.4
  - xarray=2024.06.0
  - matplotlib=3.8.4
  - cartopy=0.22.0
  - pyproj=3.6.1
  - shapely=2.0.4
  - ipython=8.24.0
